-- Subway Malaysia - Ingredients & Menu Items
-- All nutritional data per serving as provided by Subway Malaysia

INSERT INTO malaysian_foods (name_en, name_bm, aliases, category, subcategory, tags, serving_description, serving_description_en, serving_grams, calories_kcal, carbs_g, sugar_g, fiber_g, glycemic_index, gi_category, sodium_mg, potassium_mg, total_fat_g, saturated_fat_g, trans_fat_g, cholesterol_mg, protein_g, phosphorus_mg, diabetes_rating, hypertension_rating, cholesterol_rating, ckd_rating, source, verified, popularity_score) VALUES

-- 6" Sandwiches
('Subway Sliced Chicken (Ingredient)', 'Subway Sliced Chicken (Ingredient)', ARRAY['subway sliced chicken','subway chicken sandwich'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich'], '1 sandwich', '1 sandwich', 207, 300, 41, 5, NULL, NULL, NULL, NULL, NULL, 6.3, 2.7, 0.2, NULL, 20, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Chicken Teriyaki (Ingredient)', 'Subway Chicken Teriyaki (Ingredient)', ARRAY['subway teriyaki','subway teriyaki chicken'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich','sweet'], '1 sandwich', '1 sandwich', 257, 362, 46, 11, NULL, NULL, NULL, NULL, NULL, 7.3, 2.6, 0.2, NULL, 27, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Chicken Strips (Ingredient)', 'Subway Chicken Strips (Ingredient)', ARRAY['subway chicken strips sandwich'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich'], '1 sandwich', '1 sandwich', 229, 324, 39, 5, NULL, NULL, NULL, NULL, NULL, 7.1, 2.5, 0.2, NULL, 25, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Roasted Chicken Breast (Ingredient)', 'Subway Roasted Chicken Breast (Ingredient)', ARRAY['subway roasted chicken','subway roast chicken'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich'], '1 sandwich', '1 sandwich', 232, 331, 41, 6, NULL, NULL, NULL, NULL, NULL, 8.0, 3.2, 0.2, NULL, 23, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Ham (Ingredient)', 'Subway Ham (Ingredient)', ARRAY['subway ham sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich'], '1 sandwich', '1 sandwich', 221, 317, 44, 6, NULL, NULL, NULL, NULL, NULL, 7.3, 3.1, 0.2, NULL, 19, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian Meatballs (Ingredient)', 'Subway Italian Meatballs (Ingredient)', ARRAY['subway meatball','subway meatball sub'], 'fast_food', 'subway', ARRAY['fast food','sandwich'], '1 sandwich', '1 sandwich', 255, 383, 47, 8, NULL, NULL, NULL, NULL, NULL, 11.7, 5.4, 0.2, NULL, 20, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Roast Beef (Ingredient)', 'Subway Roast Beef (Ingredient)', ARRAY['subway roast beef sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','beef'], '1 sandwich', '1 sandwich', 224, 346, 40, 6, NULL, NULL, NULL, NULL, NULL, 7.1, 3.1, 0.2, NULL, 21, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Taco Beef (Ingredient)', 'Subway Taco Beef (Ingredient)', ARRAY['subway taco beef sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','beef'], '1 sandwich', '1 sandwich', 211, 320, 42, 6, NULL, NULL, NULL, NULL, NULL, 8.9, 3.6, 0.2, NULL, 17, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian B.M.T (Ingredient)', 'Subway Italian B.M.T (Ingredient)', ARRAY['subway bmt','subway italian bmt'], 'fast_food', 'subway', ARRAY['fast food','sandwich'], '1 sandwich', '1 sandwich', 229, 409, 42, 5, NULL, NULL, NULL, NULL, NULL, 16.7, 4.7, 0.2, NULL, 22, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Club (Ingredient)', 'Subway Club (Ingredient)', ARRAY['subway club sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich'], '1 sandwich', '1 sandwich', 226, 325, 41, 6, NULL, NULL, NULL, NULL, NULL, 7.1, 3.0, 0.2, NULL, 21, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Melt (Ingredient)', 'Subway Melt (Ingredient)', ARRAY['subway melt sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich'], '1 sandwich', '1 sandwich', 211, 321, 42, 5, NULL, NULL, NULL, NULL, NULL, 8.6, 3.7, 0.2, NULL, 18, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Tuna (Ingredient)', 'Subway Tuna (Ingredient)', ARRAY['subway tuna sandwich','subway tuna sub'], 'fast_food', 'subway', ARRAY['fast food','sandwich','seafood'], '1 sandwich', '1 sandwich', 239, 507, 39, 5, NULL, NULL, NULL, NULL, NULL, 29.1, 5.9, 0.9, NULL, 22, NULL, 'caution', NULL, 'limit', 'caution', 'Subway', false, 0),
('Subway Shrimp (Ingredient)', 'Subway Shrimp (Ingredient)', ARRAY['subway shrimp sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','seafood'], '1 sandwich', '1 sandwich', 186, 266, 39, 5, NULL, NULL, NULL, NULL, NULL, 5.7, 2.6, 0.2, NULL, 10, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Avocado Shrimp (Ingredient)', 'Subway Avocado Shrimp (Ingredient)', ARRAY['subway avocado shrimp sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','seafood'], '1 sandwich', '1 sandwich', 221, 340, 42, 5, NULL, NULL, NULL, NULL, NULL, 12.7, 3.7, 0.2, NULL, 11, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Mayo (Ingredient)', 'Subway Egg Mayo (Ingredient)', ARRAY['subway egg mayonnaise','subway egg mayo sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','vegetarian'], '1 sandwich', '1 sandwich', 225, 421, 41, 6, NULL, NULL, NULL, NULL, NULL, 20.7, 5.8, 0.3, NULL, 17, NULL, 'caution', NULL, 'caution', 'safe', 'Subway', false, 0),
('Subway Veggie Delight (Ingredient)', 'Subway Veggie Delight (Ingredient)', ARRAY['subway veggie','subway vegetarian'], 'fast_food', 'subway', ARRAY['fast food','sandwich','vegetarian','healthy'], '1 sandwich', '1 sandwich', 165, 250, 39, 5, NULL, NULL, NULL, NULL, NULL, 5.7, 2.5, 0.2, NULL, 10, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Diced Beef (Ingredient)', 'Subway Diced Beef (Ingredient)', ARRAY['subway diced beef sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','beef'], '1 sandwich', '1 sandwich', 236, 366, 40, 6, NULL, NULL, NULL, NULL, NULL, 10.6, 4.8, 0.3, NULL, 26, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Falafel (Ingredient)', 'Subway Falafel (Ingredient)', ARRAY['subway falafel sandwich','subway falafel sub'], 'fast_food', 'subway', ARRAY['fast food','sandwich','vegetarian'], '1 sandwich', '1 sandwich', 240, 425, 58, 9, NULL, NULL, NULL, NULL, NULL, 13.2, 5.4, 0.2, NULL, 16, NULL, 'limit', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Angus Beef (Ingredient)', 'Subway Angus Beef (Ingredient)', ARRAY['subway angus beef sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','beef','premium'], '1 sandwich', '1 sandwich', 238, 412, 44, 6, NULL, NULL, NULL, NULL, NULL, 16.1, 7.7, 0.3, NULL, 22, NULL, 'caution', NULL, 'limit', 'caution', 'Subway', false, 0),
('Subway Spicy Chicken Strips (Ingredient)', 'Subway Spicy Chicken Strips (Ingredient)', ARRAY['subway spicy chicken'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich','spicy'], '1 sandwich', '1 sandwich', 255, 369, 48, 12, NULL, NULL, NULL, NULL, NULL, 7.1, 2.4, 0.2, NULL, 28, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Sichuan Pepper Chicken (Ingredient)', 'Subway Sichuan Pepper Chicken (Ingredient)', ARRAY['subway sichuan chicken'], 'fast_food', 'subway', ARRAY['fast food','halal','sandwich','spicy'], '1 sandwich', '1 sandwich', 246, 379, 36, 5, NULL, NULL, NULL, NULL, NULL, 14.0, 5.5, 0.1, NULL, 24, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),

-- Salads
('Subway Sliced Chicken Salad (Ingredient)', 'Subway Sliced Chicken Salad (Ingredient)', ARRAY['subway sliced chicken salad','subway chicken salad'], 'fast_food', 'subway', ARRAY['fast food','halal','salad','healthy'], '1 salad', '1 salad', 346, 143, 12, 5, NULL, NULL, NULL, NULL, NULL, 5.1, 2.5, 0.1, NULL, 14, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Chicken Teriyaki Salad (Ingredient)', 'Subway Chicken Teriyaki Salad (Ingredient)', ARRAY['subway teriyaki salad','subway teriyaki chicken salad'], 'fast_food', 'subway', ARRAY['fast food','halal','salad','sweet'], '1 salad', '1 salad', 396, 205, 17, 11, NULL, NULL, NULL, NULL, NULL, 6.2, 2.4, 0.1, NULL, 22, NULL, 'safe', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Chicken Strips Salad (Ingredient)', 'Subway Chicken Strips Salad (Ingredient)', ARRAY['subway chicken strips salad'], 'fast_food', 'subway', ARRAY['fast food','halal','salad'], '1 salad', '1 salad', 368, 167, 10, 5, NULL, NULL, NULL, NULL, NULL, 5.9, 2.4, 0.1, NULL, 20, NULL, 'safe', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Roasted Chicken Breast Salad (Ingredient)', 'Subway Roasted Chicken Breast Salad (Ingredient)', ARRAY['subway roasted chicken salad','subway roast chicken salad'], 'fast_food', 'subway', ARRAY['fast food','halal','salad'], '1 salad', '1 salad', 371, 174, 13, 6, NULL, NULL, NULL, NULL, NULL, 6.9, 3.0, 0.1, NULL, 17, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Ham Salad (Ingredient)', 'Subway Ham Salad (Ingredient)', ARRAY['subway ham salad'], 'fast_food', 'subway', ARRAY['fast food','salad'], '1 salad', '1 salad', 360, 159, 15, 5, NULL, NULL, NULL, NULL, NULL, 6.2, 2.9, 0.1, NULL, 13, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian Meatballs Salad (Ingredient)', 'Subway Italian Meatballs Salad (Ingredient)', ARRAY['subway meatball salad','subway meatballs salad'], 'fast_food', 'subway', ARRAY['fast food','salad'], '1 salad', '1 salad', 394, 226, 18, 8, NULL, NULL, NULL, NULL, NULL, 10.6, 5.2, 0.1, NULL, 14, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Roast Beef Salad (Ingredient)', 'Subway Roast Beef Salad (Ingredient)', ARRAY['subway roast beef salad'], 'fast_food', 'subway', ARRAY['fast food','salad','beef'], '1 salad', '1 salad', 363, 189, 11, 6, NULL, NULL, NULL, NULL, NULL, 5.9, 2.9, 0.1, NULL, 16, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Taco Beef Salad (Ingredient)', 'Subway Taco Beef Salad (Ingredient)', ARRAY['subway taco beef salad'], 'fast_food', 'subway', ARRAY['fast food','salad','beef'], '1 salad', '1 salad', 350, 163, 13, 6, NULL, NULL, NULL, NULL, NULL, 7.8, 3.4, 0.1, NULL, 12, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian B.M.T Salad (Ingredient)', 'Subway Italian B.M.T Salad (Ingredient)', ARRAY['subway bmt salad','subway italian bmt salad'], 'fast_food', 'subway', ARRAY['fast food','salad'], '1 salad', '1 salad', 368, 252, 13, 5, NULL, NULL, NULL, NULL, NULL, 15.5, 4.6, 0.1, NULL, 17, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Club Salad (Ingredient)', 'Subway Club Salad (Ingredient)', ARRAY['subway club salad'], 'fast_food', 'subway', ARRAY['fast food','salad'], '1 salad', '1 salad', 365, 168, 13, 5, NULL, NULL, NULL, NULL, NULL, 6.0, 2.9, 0.2, NULL, 15, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Melt Salad (Ingredient)', 'Subway Melt Salad (Ingredient)', ARRAY['subway melt salad'], 'fast_food', 'subway', ARRAY['fast food','salad'], '1 salad', '1 salad', 350, 163, 13, 5, NULL, NULL, NULL, NULL, NULL, 7.5, 3.6, 0.2, NULL, 13, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Tuna Salad (Ingredient)', 'Subway Tuna Salad (Ingredient)', ARRAY['subway tuna salad'], 'fast_food', 'subway', ARRAY['fast food','salad','seafood'], '1 salad', '1 salad', 378, 350, 10, 5, NULL, NULL, NULL, NULL, NULL, 28.0, 5.8, 0.8, NULL, 16, NULL, 'safe', NULL, 'limit', 'safe', 'Subway', false, 0),
('Subway Shrimp Salad (Ingredient)', 'Subway Shrimp Salad (Ingredient)', ARRAY['subway shrimp salad'], 'fast_food', 'subway', ARRAY['fast food','salad','seafood','healthy'], '1 salad', '1 salad', 325, 108, 10, 5, NULL, NULL, NULL, NULL, NULL, 4.6, 2.4, 0.1, NULL, 5, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Avocado Shrimp Salad (Ingredient)', 'Subway Avocado Shrimp Salad (Ingredient)', ARRAY['subway avocado shrimp salad'], 'fast_food', 'subway', ARRAY['fast food','salad','seafood'], '1 salad', '1 salad', 360, 183, 13, 5, NULL, NULL, NULL, NULL, NULL, 11.6, 3.5, 0.1, NULL, 5, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Mayo Salad (Ingredient)', 'Subway Egg Mayo Salad (Ingredient)', ARRAY['subway egg mayonnaise salad','subway egg mayo salad'], 'fast_food', 'subway', ARRAY['fast food','salad','vegetarian'], '1 salad', '1 salad', 364, 264, 13, 6, NULL, NULL, NULL, NULL, NULL, 19.6, 5.6, 0.2, NULL, 11, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Veggie Delight Salad (Ingredient)', 'Subway Veggie Delight Salad (Ingredient)', ARRAY['subway veggie salad','subway vegetarian salad'], 'fast_food', 'subway', ARRAY['fast food','salad','vegetarian','healthy'], '1 salad', '1 salad', 304, 93, 10, 5, NULL, NULL, NULL, NULL, NULL, 4.5, 2.4, 0.1, NULL, 5, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Chicken Strip Energy Bowl (Ingredient)', 'Subway Chicken Strip Energy Bowl (Ingredient)', ARRAY['subway chicken energy bowl','subway chicken bowl'], 'fast_food', 'subway', ARRAY['fast food','halal','bowl','salad'], '1 bowl', '1 bowl', 359, 276, 21, 14, NULL, NULL, NULL, NULL, NULL, 12.9, 4.6, 0.2, NULL, 21, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Falafel Energy Bowl (Ingredient)', 'Subway Falafel Energy Bowl (Ingredient)', ARRAY['subway falafel bowl','subway falafel energy bowl'], 'fast_food', 'subway', ARRAY['fast food','bowl','salad','vegetarian'], '1 bowl', '1 bowl', 370, 404, 33, 12, NULL, NULL, NULL, NULL, NULL, 23.9, 6.2, 0.2, NULL, 13, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Taco Beef Energy Bowl (Ingredient)', 'Subway Taco Beef Energy Bowl (Ingredient)', ARRAY['subway taco beef bowl','subway beef energy bowl'], 'fast_food', 'subway', ARRAY['fast food','bowl','salad','beef'], '1 bowl', '1 bowl', 341, 362, 15, 7.6, NULL, NULL, NULL, NULL, NULL, 26.5, 7.5, 0.4, NULL, 18, NULL, 'safe', NULL, 'limit', 'safe', 'Subway', false, 0),

-- Breakfast Sandwiches
('Subway Egg & Cheese (Ingredient)', 'Subway Egg & Cheese (Ingredient)', ARRAY['subway egg cheese sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','breakfast','vegetarian'], '1 sandwich', '1 sandwich', 125, 276, 37, 3, NULL, NULL, NULL, NULL, NULL, 7.6, 2.7, 0.2, NULL, 15, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Ham & Egg (Ingredient)', 'Subway Ham & Egg (Ingredient)', ARRAY['subway ham egg sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','breakfast'], '1 sandwich', '1 sandwich', 153, 309, 39, 4, NULL, NULL, NULL, NULL, NULL, 8.4, 3.0, 0.2, NULL, 19, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Steak, Egg & Cheese (Ingredient)', 'Subway Steak, Egg & Cheese (Ingredient)', ARRAY['subway steak egg cheese'], 'fast_food', 'subway', ARRAY['fast food','sandwich','breakfast','beef'], '1 sandwich', '1 sandwich', 160, 341, 39, 3, NULL, NULL, NULL, NULL, NULL, 10.8, 4.3, 0.2, NULL, 20, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Bacon & Egg (Ingredient)', 'Subway Bacon & Egg (Ingredient)', ARRAY['subway bacon egg sandwich'], 'fast_food', 'subway', ARRAY['fast food','sandwich','breakfast'], '1 sandwich', '1 sandwich', 135, 324, 37, 3, NULL, NULL, NULL, NULL, NULL, 11.2, 4.3, 0.2, NULL, 18, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Proteins (Separate Portions)
('Subway Sliced Chicken 3 Slices (Ingredient)', 'Subway Sliced Chicken 3 Slices (Ingredient)', ARRAY['subway chicken slices'], 'fast_food', 'subway', ARRAY['fast food','halal','protein','topping'], '3 keping', '3 slices', 42, 50, 1, 0, NULL, NULL, NULL, NULL, NULL, 0.6, 0.1, 0.0, NULL, 10, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Sliced Chicken 1 Slice (Ingredient)', 'Subway Sliced Chicken 1 Slice (Ingredient)', ARRAY['subway chicken slice'], 'fast_food', 'subway', ARRAY['fast food','halal','protein','topping'], '1 keping', '1 slice', 14, 17, 0, 0, NULL, NULL, NULL, NULL, NULL, 0.2, 0.0, 0.0, NULL, 3, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Chicken Teriyaki Protein (Ingredient)', 'Subway Chicken Teriyaki Protein (Ingredient)', ARRAY['subway teriyaki chicken portion'], 'fast_food', 'subway', ARRAY['fast food','halal','protein','topping'], '1 bahagian', '1 portion', 92, 112, 7, 6, NULL, NULL, NULL, NULL, NULL, 1.6, 0.0, 0.0, NULL, 17, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Chicken Strips Protein (Ingredient)', 'Subway Chicken Strips Protein (Ingredient)', ARRAY['subway chicken strips portion'], 'fast_food', 'subway', ARRAY['fast food','halal','protein','topping'], '1 bahagian', '1 portion', 64, 74, 0, 0, NULL, NULL, NULL, NULL, NULL, 1.4, 0.0, 0.0, NULL, 15, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Oven Roasted Chicken Breast Protein (Ingredient)', 'Subway Oven Roasted Chicken Breast Protein (Ingredient)', ARRAY['subway roasted chicken portion'], 'fast_food', 'subway', ARRAY['fast food','halal','protein','topping'], '1 bahagian', '1 portion', 67, 81, 2, 2, NULL, NULL, NULL, NULL, NULL, 2.3, 0.7, 0.0, NULL, 13, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Ham 4 Slices (Ingredient)', 'Subway Ham 4 Slices (Ingredient)', ARRAY['subway ham slices'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '4 keping', '4 slices', 56, 67, 4, 1, NULL, NULL, NULL, NULL, NULL, 1.7, 0.6, 0.0, NULL, 8, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Ham 1 Slice (Ingredient)', 'Subway Ham 1 Slice (Ingredient)', ARRAY['subway ham slice'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 keping', '1 slice', 14, 17, 1, 0, NULL, NULL, NULL, NULL, NULL, 0.4, 0.1, 0.0, NULL, 2, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Bacon 2 Strips (Ingredient)', 'Subway Bacon 2 Strips (Ingredient)', ARRAY['subway bacon strips'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '2 jalur', '2 strips', 9, 48, 0, 0, NULL, NULL, NULL, NULL, NULL, 3.6, 1.7, 0.0, NULL, 3, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Bacon 1 Strip (Ingredient)', 'Subway Bacon 1 Strip (Ingredient)', ARRAY['subway bacon strip'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 jalur', '1 strip', 5, 24, 0, 0, NULL, NULL, NULL, NULL, NULL, 1.8, 0.8, 0.0, NULL, 2, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian Meatballs Protein (Ingredient)', 'Subway Italian Meatballs Protein (Ingredient)', ARRAY['subway meatballs portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 bahagian', '1 portion', 90, 133, 8, 3, NULL, NULL, NULL, NULL, NULL, 6.1, 2.8, 0.0, NULL, 10, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Roast Beef 3 Slices (Ingredient)', 'Subway Roast Beef 3 Slices (Ingredient)', ARRAY['subway roast beef slices'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','beef'], '3 keping', '3 slices', 59, 96, 1, 1, NULL, NULL, NULL, NULL, NULL, 1.4, 0.5, 0.0, NULL, 11, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Roast Beef 1 Slice (Ingredient)', 'Subway Roast Beef 1 Slice (Ingredient)', ARRAY['subway roast beef slice'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','beef'], '1 keping', '1 slice', 20, 32, 0, 0, NULL, NULL, NULL, NULL, NULL, 0.5, 0.2, 0.0, NULL, 4, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Taco Beef Protein (Ingredient)', 'Subway Taco Beef Protein (Ingredient)', ARRAY['subway taco beef portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','beef'], '1 bahagian', '1 portion', 46, 70, 3, 1, NULL, NULL, NULL, NULL, NULL, 3.2, 1.1, 0.0, NULL, 7, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian B.M.T Protein (Ingredient)', 'Subway Italian B.M.T Protein (Ingredient)', ARRAY['subway bmt portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 bahagian', '1 portion', 64, 159, 3, 1, NULL, NULL, NULL, NULL, NULL, 11.0, 2.2, 0.0, NULL, 12, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Club Protein (Ingredient)', 'Subway Club Protein (Ingredient)', ARRAY['subway club portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 bahagian', '1 portion', 62, 75, 2, 1, NULL, NULL, NULL, NULL, NULL, 1.5, 0.5, 0.0, NULL, 10, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Salami 1 Slice (Ingredient)', 'Subway Salami 1 Slice (Ingredient)', ARRAY['subway salami slice'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 keping', '1 slice', 6, 24, 0, 0, NULL, NULL, NULL, NULL, NULL, 2.0, 0.1, 0.0, NULL, 1, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Pepperoni 1 Slice (Ingredient)', 'Subway Pepperoni 1 Slice (Ingredient)', ARRAY['subway pepperoni slice'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 keping', '1 slice', 6, 18, 0, 0, NULL, NULL, NULL, NULL, NULL, 1.4, 0.6, 0.0, NULL, 1, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Melt Protein (Ingredient)', 'Subway Melt Protein (Ingredient)', ARRAY['subway melt portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping'], '1 bahagian', '1 portion', 47, 71, 3, 1, NULL, NULL, NULL, NULL, NULL, 2.9, 1.2, 0.0, NULL, 8, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Tuna Protein (Ingredient)', 'Subway Tuna Protein (Ingredient)', ARRAY['subway tuna portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','seafood'], '1 bahagian', '1 portion', 74, 257, 0, 0, NULL, NULL, NULL, NULL, NULL, 23.5, 3.4, 0.7, NULL, 12, NULL, 'safe', NULL, 'limit', 'safe', 'Subway', false, 0),
('Subway Shrimp Protein (Ingredient)', 'Subway Shrimp Protein (Ingredient)', ARRAY['subway shrimp portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','seafood'], '1 bahagian', '1 portion', 30, 22, 0, 0, NULL, NULL, NULL, NULL, NULL, 0.1, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Mayo Protein (Ingredient)', 'Subway Egg Mayo Protein (Ingredient)', ARRAY['subway egg mayo portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','vegetarian'], '1 bahagian', '1 portion', 60, 171, 2, 1, NULL, NULL, NULL, NULL, NULL, 15.1, 3.2, 0.1, NULL, 7, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Patty (Ingredient)', 'Subway Egg Patty (Ingredient)', ARRAY['subway egg'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','vegetarian'], '1 biji', '1 patty', 45, 41, 1, 0, NULL, NULL, NULL, NULL, NULL, 2.1, 0.2, 0.0, NULL, 5, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Avocado (Ingredient)', 'Subway Avocado (Ingredient)', ARRAY['subway avocado topping'], 'fast_food', 'subway', ARRAY['fast food','topping','vegetarian','healthy'], '1 bahagian', '1 portion', 35, 75, 2, 0, NULL, NULL, NULL, NULL, NULL, 7.0, 1.1, 0.0, NULL, 1, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway American Cheese 2 Slices (Ingredient)', 'Subway American Cheese 2 Slices (Ingredient)', ARRAY['subway american cheese slices'], 'fast_food', 'subway', ARRAY['fast food','cheese','topping'], '2 keping', '2 slices', 11, 40, 1, 0, NULL, NULL, NULL, NULL, NULL, 3.5, 2.2, 0.1, NULL, 2, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway American Cheese 1 Slice (Ingredient)', 'Subway American Cheese 1 Slice (Ingredient)', ARRAY['subway american cheese slice'], 'fast_food', 'subway', ARRAY['fast food','cheese','topping'], '1 keping', '1 slice', 6, 20, 0, 0, NULL, NULL, NULL, NULL, NULL, 1.7, 1.1, 0.1, NULL, 1, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Shredded Cheese (Ingredient)', 'Subway Shredded Cheese (Ingredient)', ARRAY['subway shredded cheese'], 'fast_food', 'subway', ARRAY['fast food','cheese','topping'], '1 sudu', '1 scoop', 14, 54, 1, 0, NULL, NULL, NULL, NULL, NULL, 4.2, 2.4, 0.2, NULL, 3, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Falafel 3 Pieces (Ingredient)', 'Subway Falafel 3 Pieces (Ingredient)', ARRAY['subway falafel pieces'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','vegetarian'], '3 biji', '3 pieces', 75, 175, 19, 4, NULL, NULL, NULL, NULL, NULL, 7.6, 2.9, 0.0, NULL, 6, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Falafel 1 Piece (Ingredient)', 'Subway Falafel 1 Piece (Ingredient)', ARRAY['subway falafel piece'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','vegetarian'], '1 biji', '1 piece', 25, 58, 6, 1, NULL, NULL, NULL, NULL, NULL, 2.5, 1.0, 0.0, NULL, 2, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Black Pepper Pork (Ingredient)', 'Subway Black Pepper Pork (Ingredient)', ARRAY['subway black pepper pork portion'], 'fast_food', 'subway', ARRAY['fast food','protein','topping','pork'], '1 bahagian', '1 portion', 80, 140, 3.3, 1.3, NULL, NULL, NULL, NULL, NULL, 6.8, 1.8, 0.0, NULL, 16, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Breads
('Subway White Bread (Ingredient)', 'Subway White Bread (Ingredient)', ARRAY['subway white bread','subway white'], 'fast_food', 'subway', ARRAY['fast food','bread'], '1 roti', '1 bread', 67, 195, 35, 3, NULL, NULL, NULL, NULL, NULL, 2.5, 0.3, 0.1, NULL, 7, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Wheat Bread (Ingredient)', 'Subway Wheat Bread (Ingredient)', ARRAY['subway wheat bread','subway wheat'], 'fast_food', 'subway', ARRAY['fast food','bread'], '1 roti', '1 bread', 69, 195, 35, 3, NULL, NULL, NULL, NULL, NULL, 2.1, 0.3, 0.1, NULL, 8, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Honey Oat Bread (Ingredient)', 'Subway Honey Oat Bread (Ingredient)', ARRAY['subway honey oat bread','subway honey oat'], 'fast_food', 'subway', ARRAY['fast food','bread'], '1 roti', '1 bread', 73, 210, 38, 4, NULL, NULL, NULL, NULL, NULL, 2.3, 0.4, 0.1, NULL, 8, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Parmesan Oregano Bread (Ingredient)', 'Subway Parmesan Oregano Bread (Ingredient)', ARRAY['subway parmesan oregano bread','subway parmesan'], 'fast_food', 'subway', ARRAY['fast food','bread'], '1 roti', '1 bread', 70, 206, 37, 3, NULL, NULL, NULL, NULL, NULL, 2.7, 0.4, 0.1, NULL, 8, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Spinach Wrap (Ingredient)', 'Subway Spinach Wrap (Ingredient)', ARRAY['subway spinach wrap','subway wrap'], 'fast_food', 'subway', ARRAY['fast food','bread','wrap'], '1 wrap', '1 wrap', 65, 196, 32, 2, NULL, NULL, NULL, NULL, NULL, 5.4, 2.8, 0.0, NULL, 5, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Sauces
('Subway Chipotle Southwest Sauce (Ingredient)', 'Subway Chipotle Southwest Sauce (Ingredient)', ARRAY['subway chipotle sauce'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment','spicy'], '1 sudu', '1 tbsp', 14, 66, 1, 1, NULL, NULL, NULL, NULL, NULL, 6.7, 1.2, 0.1, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Yellow Mustard (Ingredient)', 'Subway Yellow Mustard (Ingredient)', ARRAY['subway mustard'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 14, 9, 1, 0, NULL, NULL, NULL, NULL, NULL, 0.6, 0.0, 0.0, NULL, 1, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Marinara Sauce (Ingredient)', 'Subway Marinara Sauce (Ingredient)', ARRAY['subway marinara'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 14, 10, 2, 1, NULL, NULL, NULL, NULL, NULL, 0.2, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Sweet Onion Sauce (Ingredient)', 'Subway Sweet Onion Sauce (Ingredient)', ARRAY['subway sweet onion'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment','sweet'], '1 sudu', '1 tbsp', 18, 33, 8, 7, NULL, NULL, NULL, NULL, NULL, 0.1, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Honey Mustard Sauce (Ingredient)', 'Subway Honey Mustard Sauce (Ingredient)', ARRAY['subway honey mustard'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment','sweet'], '1 sudu', '1 tbsp', 14, 21, 5, 4, NULL, NULL, NULL, NULL, NULL, 0.1, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Mayonnaise (Ingredient)', 'Subway Mayonnaise (Ingredient)', ARRAY['subway mayo'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 14, 100, 0, 0, NULL, NULL, NULL, NULL, NULL, 11.0, 1.5, 0.3, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Olive Oil (Ingredient)', 'Subway Olive Oil (Ingredient)', ARRAY['subway olive oil'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment','oil'], '1 sudu', '1 tbsp', 5, 44, 0, 0, NULL, NULL, NULL, NULL, NULL, 4.9, 0.3, 0.1, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Red Wine Vinegar (Ingredient)', 'Subway Red Wine Vinegar (Ingredient)', ARRAY['subway vinegar'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 4, 0.3, 0.1, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Italian Dressing (Ingredient)', 'Subway Italian Dressing (Ingredient)', ARRAY['subway italian dressing'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 14, 14.8, 3.6, 3.3, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Thousand Island Sauce (Ingredient)', 'Subway Thousand Island Sauce (Ingredient)', ARRAY['subway thousand island'], 'fast_food', 'subway', ARRAY['fast food','sauce','condiment'], '1 sudu', '1 tbsp', 14, 36.7, 3.0, 2.4, NULL, NULL, NULL, NULL, NULL, 2.7, 0.5, 0.0, NULL, 0.2, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Vegetables
('Subway Lettuce (Ingredient)', 'Subway Lettuce (Ingredient)', ARRAY['subway lettuce topping'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping','healthy'], '1 bahagian', '1 portion', 21, 3, 0.4, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Tomato (Ingredient)', 'Subway Tomato (Ingredient)', ARRAY['subway tomato topping'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping','healthy'], '1 bahagian', '1 portion', 35, 6, 1, 1, NULL, NULL, NULL, NULL, NULL, 0.1, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Cucumber (Ingredient)', 'Subway Cucumber (Ingredient)', ARRAY['subway cucumber topping'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping','healthy'], '1 bahagian', '1 portion', 14, 2, 1, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Onion (Ingredient)', 'Subway Onion (Ingredient)', ARRAY['subway onion topping'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping'], '1 bahagian', '1 portion', 7, 3, 1, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Green Pepper (Ingredient)', 'Subway Green Pepper (Ingredient)', ARRAY['subway green pepper topping'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping'], '1 bahagian', '1 portion', 7, 1, 0.3, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Pickle 3 Slices (Ingredient)', 'Subway Pickle 3 Slices (Ingredient)', ARRAY['subway pickle slices'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping'], '3 keping', '3 slices', 9, 1, 0.2, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Olive 3 Slices (Ingredient)', 'Subway Olive 3 Slices (Ingredient)', ARRAY['subway olive slices'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping'], '3 keping', '3 slices', 3, 4, 0.2, 0, NULL, NULL, NULL, NULL, NULL, 0.3, 0.1, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Jalapeno 3 Slices (Ingredient)', 'Subway Jalapeno 3 Slices (Ingredient)', ARRAY['subway jalapeno slices','subway jalapeno'], 'fast_food', 'subway', ARRAY['fast food','vegetable','topping','spicy'], '3 keping', '3 slices', 4, 2, 0.2, 0, NULL, NULL, NULL, NULL, NULL, 0.0, 0.0, 0.0, NULL, 0, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Soups
('Subway Corn Chowder Soup (Ingredient)', 'Subway Corn Chowder Soup (Ingredient)', ARRAY['subway corn soup'], 'fast_food', 'subway', ARRAY['fast food','soup'], '1 mangkuk', '1 bowl', 236, 153, 25, 7, NULL, NULL, NULL, NULL, NULL, 4.7, 2.5, 0.2, NULL, 3, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Broccoli Cheese Soup (Ingredient)', 'Subway Broccoli Cheese Soup (Ingredient)', ARRAY['subway broccoli cheese soup'], 'fast_food', 'subway', ARRAY['fast food','soup'], '1 mangkuk', '1 bowl', 236, 187, 45, 4, NULL, NULL, NULL, NULL, NULL, 13.1, 8.1, 0.5, NULL, 4, NULL, 'limit', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Wraps
('Subway Chicken Strip Wrap (Ingredient)', 'Subway Chicken Strip Wrap (Ingredient)', ARRAY['subway chicken wrap'], 'fast_food', 'subway', ARRAY['fast food','halal','wrap'], '1 wrap', '1 wrap', 191, 398, 34, 3, NULL, NULL, NULL, NULL, NULL, 17.8, 6.6, 0.2, NULL, 26, NULL, 'caution', NULL, 'safe', 'caution', 'Subway', false, 0),
('Subway Taco Beef Wrap (Ingredient)', 'Subway Taco Beef Wrap (Ingredient)', ARRAY['subway beef wrap'], 'fast_food', 'subway', ARRAY['fast food','wrap','beef'], '1 wrap', '1 wrap', 173, 394, 37, 4, NULL, NULL, NULL, NULL, NULL, 19.7, 7.6, 0.2, NULL, 18, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Falafel Wrap (Ingredient)', 'Subway Falafel Wrap (Ingredient)', ARRAY['subway falafel wrap vegetarian'], 'fast_food', 'subway', ARRAY['fast food','wrap','vegetarian'], '1 wrap', '1 wrap', 162, 398, 35, 4, NULL, NULL, NULL, NULL, NULL, 23.8, 8.3, 0.5, NULL, 12, NULL, 'caution', NULL, 'limit', 'safe', 'Subway', false, 0),
('Subway B.L.T. Wrap (Ingredient)', 'Subway B.L.T. Wrap (Ingredient)', ARRAY['subway blt wrap','subway bacon lettuce tomato wrap'], 'fast_food', 'subway', ARRAY['fast food','wrap'], '1 wrap', '1 wrap', 191, 534, 46, 6, NULL, NULL, NULL, NULL, NULL, 31.4, 8.8, 0.5, NULL, 15, NULL, 'caution', NULL, 'limit', 'safe', 'Subway', false, 0),

-- Sides
('Subway Hash Brown (Ingredient)', 'Subway Hash Brown (Ingredient)', ARRAY['subway hashbrown'], 'fast_food', 'subway', ARRAY['fast food','side','breakfast'], '1 biji', '1 piece', 53, 115, 12, 0.4, NULL, NULL, NULL, NULL, NULL, 6.7, 1.5, 0.1, NULL, 1.4, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Mayo 2 Scoops (Ingredient)', 'Subway Egg Mayo 2 Scoops (Ingredient)', ARRAY['subway egg mayo 2 scoops'], 'fast_food', 'subway', ARRAY['fast food','side','topping','vegetarian'], '2 sudu', '2 scoops', 60, 171, 2.3, 1.3, NULL, NULL, NULL, NULL, NULL, 15.1, 3.2, 0.1, NULL, 6.5, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),
('Subway Egg Mayo 1 Scoop (Ingredient)', 'Subway Egg Mayo 1 Scoop (Ingredient)', ARRAY['subway egg mayo 1 scoop'], 'fast_food', 'subway', ARRAY['fast food','side','topping','vegetarian'], '1 sudu', '1 scoop', 30, 86, 1.2, 0.7, NULL, NULL, NULL, NULL, NULL, 7.5, 1.6, 0.0, NULL, 3.3, NULL, 'safe', NULL, 'safe', 'safe', 'Subway', false, 0),

-- Cookies
('Subway White Chocolate Macadamia Nut Cookie (Ingredient)', 'Subway White Chocolate Macadamia Nut Cookie (Ingredient)', ARRAY['subway white chocolate cookie','subway macadamia cookie'], 'fast_food', 'subway', ARRAY['fast food','dessert','cookie'], '1 keping', '1 cookie', 45, 217, 28, 18, NULL, NULL, NULL, NULL, NULL, 10.8, 5.4, 0.1, NULL, 2, NULL, 'limit', NULL, 'caution', 'safe', 'Subway', false, 0),
('Subway Chocolate Chip Cookie (Ingredient)', 'Subway Chocolate Chip Cookie (Ingredient)', ARRAY['subway choc chip cookie'], 'fast_food', 'subway', ARRAY['fast food','dessert','cookie'], '1 keping', '1 cookie', 45, 220, 30, 18, NULL, NULL, NULL, NULL, NULL, 10.4, 5.5, 0.1, NULL, 2, NULL, 'limit', NULL, 'caution', 'safe', 'Subway', false, 0),
('Subway Double Chocolate Chip Cookie (Ingredient)', 'Subway Double Chocolate Chip Cookie (Ingredient)', ARRAY['subway double chocolate cookie'], 'fast_food', 'subway', ARRAY['fast food','dessert','cookie'], '1 keping', '1 cookie', 45, 200, 28, 19, NULL, NULL, NULL, NULL, NULL, 8.9, 5.1, 0.1, NULL, 2, NULL, 'limit', NULL, 'caution', 'safe', 'Subway', false, 0),
('Subway Oatmeal Raisin Cookie (Ingredient)', 'Subway Oatmeal Raisin Cookie (Ingredient)', ARRAY['subway oatmeal cookie','subway raisin cookie'], 'fast_food', 'subway', ARRAY['fast food','dessert','cookie'], '1 keping', '1 cookie', 45, 187, 28, 11, NULL, NULL, NULL, NULL, NULL, 7.6, 3.6, 0.1, NULL, 2, NULL, 'caution', NULL, 'safe', 'safe', 'Subway', false, 0);

